### ISSUE TITLE
Audio glitch on startup

### ISSUE THREAD

**Issue by emoose** [ElDewrito/DewRecode#11]
When the game starts up I get a weird squeak through my headphones, only lasts less than a second but it happens every time the game starts.
Also seems to happen with latest ED, not sure if it was something added to ED recently (and ported over to DR) or if it's maybe Win10 related.

**Comment by twist84** [comment]
I get that too and I'm on Win8.1

**Comment by emoose** [comment]
Well that's weird, I'll update the title now.
Do you get it with both ED and DR?
I know it never happened before the VoIP/HTML5 changes were added in, but I just tested with all the plugins removed and it still happens though, so we can rule out IRC/VoIP/RCON/Info server being the cause.

**Comment by twist84** [comment]
No it only happens in DR for me at least.

**Comment by PersonalityPi** [comment]
Happens in Both for me.

**Comment by emoose** [comment]
Strange, I'll try out ED 0.4.5 later and see if happens with that, if it doesn't I'll have to try going through all the commits after that to see when it started.

**Comment by PersonalityPi** [comment]
Okay I can confirm it isn't HTML or VOIP it happened before both of them.

**Comment by PersonalityPi** [comment]
Persists on 0.4.5

**Comment by PersonalityPi** [comment]
Seems to happen on other games. Probably Hardware/Driver related.

**Comment by NoShotz** [comment]
Since i upgraded to windows 10, it started happening on ED, along with a game called war thunder

**Comment by Shockfire** [comment]
Upgraded to Windows 10 and I can confirm I'm getting this now. Never happened before.

**Comment by emoose** [comment]
As people said on IRC this doesn't seem to be an ElDorito issue, tried HO without ED and the audio glitch still happens.

Leaving this open in case someone wants to try fixing it though (maybe FMOD related?), although I guess it'd probably get fixed in a Win10 update eventually.
