### ISSUE TITLE
Debug Log Buffer Issues

### ISSUE THREAD

**Issue by Ernegien** [ElDewrito/DewRecode#20]
Running the 'help' command (and others I'm sure) overflows the 4kb buffer in the DebugLog::Log function and crashes the game.  Will need to stream or perform multiple passes over that buffer when writing text to the debug log.

**Comment by Ernegien** [comment]
Well, it asserts, instead of overflows since the secure string function is obviously being used :)

**Comment by emoose** [comment]
Should be fixed now, we check if the format string is bigger than 4096, if it is then it doesn't output it to the log file.
