### ISSUE TITLE
MainMenu Checks / Host Checks

### ISSUE THREAD

**Issue by PersonalityPi** [ElDewrito/DewRecode#21]
When using Connect iphere the check that trys to check if your on the mainmenu ALWAYS says your not.  Also, when using host commands like Server.Cheats it doesn't seem to understand when you are the host/or in the lobby like it asks.

(Probably just unfinished code but I thought I would report it anyway)

**Comment by Shockfire** [comment]
If we copy over the BlamNetwork files from the custom-packets branch, this would be trivial to fix. Session::IsEstablished() can be used to check if you're in a lobby and Session::IsHost() can be used to check if you're the host. Those functions do exactly what the game does to check those things and should work flawlessly.

**Comment by PersonalityPi** [comment]
Mainmenu hook now works c: Just the Hosts now

**Comment by PersonalityPi** [comment]
All fixed
