### ISSUE TITLE
No respawn counter.

### ISSUE THREAD

**Issue by craftycodie** [ElDewrito/DewRecode#36]
I'm aware that the respawn counter was removed very early on because it came with all the loadout stuff, but a dev told me that the Halo 3 counter alone was still in the game. Hopefully if it can be enabled it'll fix some other bugs related to the death camera.

**Comment by emoose** [comment]
If we can find where in H3E it gets drawn we can probably reimplement it in HO easily, afaik the strings are still here, it's just missing code to print it.

**Comment by craftycodie** [comment]
Yeah the strings are definitely there,  do you think that it'd be possible to fix the spectating on death too? Only I ask because in limited life games on death the camera just sticks to the corpse for a while,  it'll eventually switch to a player but if they die thats it.  Obviously my knowledge is very limited but I was wondering  if the spectating stuff would be close to where the respawn counter is drawn.

**Comment by craftycodie** [comment]
Fixed with tag changes.
