### ISSUE TITLE
Fix the halo 3 scoreboard? (More of a problem if Multi-Team is fixed.)

### ISSUE THREAD

**Issue by craftycodie** [ElDewrito/DewRecode#37]
I know that this isn't required as the current one works fine,  but I've had a lot of requests for this now and it's currently beyond me.  The scoreboard seem to be having an issue listing players but everything else seems to function, everything else being team scores, winning team display and titles. 

Edit: This'll likely be the best way to handle the scoring with multi-team if that ever comes back.

**Comment by Gliby** [comment]
The Halo 3 scoreboard would be a neat addition.

**Comment by craftycodie** [comment]
Not an issue. 
The scaleform scoreboard is now a viable solution, so is an overlay.
