### ISSUE TITLE
Add dual-wielding back into the game

### ISSUE THREAD

**Issue by emoose** [ElDewrito/DewRecode#9]
Weapons still seem to have the required flags set, not sure if the game is actually reading those flags though.

Not even sure if the game still has code to print the second "Press X to dual-wield" text on the HUD. I'm pretty sure I heard early on that HO was having dual-wielding as a special ability / P2W option though, but I can't find anything about it anywhere.

**Comment by emoose** [comment]
Fixed in d894125a95cb765b661f9dd339435c94c98b1e33

**Comment by Shockfire** [comment]
:O how did you fix it?

**Comment by MickeyYoofers** [comment]
what key are you really even supposed to press to dual wield, though?
